### PR TITLE
Init directory for English translations

### PR DESCRIPTION
**Pull request by tsaiDavid**
##### Description of change

Thanks for all your hard work on these libraries. My peers and I are currently evaluating usage of the `G2` library and thought it would be beneficial to create a directory for us to begin submitting English translations - would appreciate feedback here.

### CODE REVIEW

**Comment by alberttsou** [comment]
My team needs this as well so I will be able to contribute to this translation effort.

**Comment by leungwensen** [comment]
@tsaiDavid 

Thank you very much for your contribution!
Before we merge the PR, could you rename the directory `us-en` to `en-us`? We want to keep it the same form as `zh-cn`(language-location).

**Comment by tsaiDavid** [comment]
Absolutely, no problem. I’ll get to it ASAP. What else is needed to get this wired up for switching between languages? Is there a preferred order to translating?

**Comment by tsaiDavid** [comment]
@leungwensen - all done!

**Comment by leungwensen** [comment]
@tsaiDavid It would be best to prioritize the translating of API documents and tutorials.

**Comment by tsaiDavid** [comment]
@leungwensen - sounds good, thank you.

Tagging @alberttsou for visibility, he's wanted to work on this as well.

**Pull request merged**
